version: "3.8"

services:
  traefik:
    image: traefik:v2.10
    container_name: traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"      # Traefik Web proxy
      - "8080:8080"  # Traefik Dashboard (development view)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  importer-app:
    build: .
    container_name: dhis2-importer
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "8005:8000" # Direct port mapping for FastAPI Web Server (using 8005 to avoid host conflicts)
    labels:
      - "traefik.enable=true"
      # Route Web Importer App to http://dhis2-importer.localhost
      - "traefik.http.routers.importer.rule=Host(`dhis2-importer.localhost`)"
      - "traefik.http.routers.importer.entrypoints=web"
      - "traefik.http.services.importer.loadbalancer.server.port=8000"
    depends_on:
      - traefik
