data_elements:
  # SOURCE_DE_UID: DEST_DE_UID
  xA01Im2qXJ2: "DEST_DE_xA01"
  OIf5MUDkGjc: "DEST_DE_OIf5"
  ikB8Ocarx3u: "DEST_DE_ikB8"
  lUMKo1erWQ5: "DEST_DE_lUMK"
  aXVGlFzOtno: "DEST_DE_aXVG"
  sQqYMjbB8HR: "DEST_DE_sQqY"
  JAG1MYpzgxl: "DEST_DE_JAG1"
  MLUe29EGZG0: "DEST_DE_MLUe"
  gwoemF7NzFs: "DEST_DE_gwoe"

organisation_units:
  # SOURCE_OU_UID: DEST_OU_UID
  x1WEJQu4rJp: "DEST_OU_x1WE"
  OU_SOURCE_001: "DEST_OU_001"
  OU_SOURCE_002: "DEST_OU_002"

category_option_combos:
  default: "DEFAULT_COC_UID"
