partners:
  MZ-PATHFINDER:
    attribute_option_combo: PARTNER_AOC_UID
    name: MZ-PATHFINDER
  MZ-PSI:
    attribute_option_combo: PSI_AOC_UID
    name: MZ-PSI
reports:
  pathfinder_monthly:
    data_set: Nrl1hP8S0mR
    name: Pathfinder Malaria Report
    pivot_table_url: /api/analytics.csv?dimension=dx:xA01Im2qXJ2;OIf5MUDkGjc;ikB8Ocarx3u;lUMKo1erWQ5;aXVGlFzOtno;sQqYMjbB8HR;JAG1MYpzgxl;MLUe29EGZG0;gwoemF7NzFs&dimension=ou:x1WEJQu4rJp;LEVEL-a2bG40SHomq&dimension=pe:{period}&tableLayout=true&columns=dx&rows=ou;pe&skipRounding=false&completedOnly=false&hideEmptyRows=true
    source_id: pathfinder_server
  psi_monthly:
    data_set: DESTINATION_DATASET_UID
    name: PSI Monthly Facility Report
    pivot_table_url: /api/analytics.csv?dimension=dx:xA01Im2qXJ2;OIf5MUDkGjc&dimension=ou:LEVEL-2&dimension=pe:{period}&tableLayout=true&columns=dx&rows=ou;pe
    source_id: psi_server
sources:
  pathfinder_server:
    base_url: https://data.psi-mis.org
    name: Pathfinder Server
    password: pathfinder_password
    username: pathfinder_user
  psi_server:
    base_url: https://another-dhis2.org
    name: PSI Server
    password: psi_password
    username: psi_user
