partners:
  MZ-PATHFINDER:
    name: "MZ-PATHFINDER"
    attribute_option_combo: "PARTNER_AOC_UID"
  MZ-PSI:
    name: "MZ-PSI"
    attribute_option_combo: "PSI_AOC_UID"

sources:
  pathfinder_server:
    name: "Pathfinder Server"
    base_url: "https://data.psi-mis.org"
    username: "pathfinder_user"
    password: "pathfinder_password"
  psi_server:
    name: "PSI Server"
    base_url: "https://another-dhis2.org"
    username: "psi_user"
    password: "psi_password"

reports:
  pathfinder_monthly:
    name: "Pathfinder Malaria Report"
    pivot_table_url: "/api/analytics.csv?dimension=dx:xA01Im2qXJ2;OIf5MUDkGjc;ikB8Ocarx3u;lUMKo1erWQ5;aXVGlFzOtno;sQqYMjbB8HR;JAG1MYpzgxl;MLUe29EGZG0;gwoemF7NzFs&dimension=ou:x1WEJQu4rJp;LEVEL-a2bG40SHomq&dimension=pe:{period}&tableLayout=true&columns=dx&rows=ou;pe&skipRounding=false&completedOnly=false&hideEmptyRows=true"
    source_id: "pathfinder_server"
    data_set: "Nrl1hP8S0mR"
  psi_monthly:
    name: "PSI Monthly Facility Report"
    pivot_table_url: "/api/analytics.csv?dimension=dx:xA01Im2qXJ2;OIf5MUDkGjc&dimension=ou:LEVEL-2&dimension=pe:{period}&tableLayout=true&columns=dx&rows=ou;pe"
    source_id: "psi_server"
    data_set: "DESTINATION_DATASET_UID"
